package pt.unl.fct.di.novasys.babel.core;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.security.KeyStore;
import java.security.Provider;
import java.security.KeyStore.ProtectionParameter;
import java.security.KeyStoreException;
import java.security.NoSuchAlgorithmException;
import java.util.function.Supplier;

import javax.security.auth.callback.Callback;
import javax.security.auth.callback.PasswordCallback;
import javax.security.auth.callback.UnsupportedCallbackException;

import java.security.Security;
import java.security.cert.CertificateException;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.bouncycastle.jce.provider.BouncyCastleProvider;

import pt.unl.fct.di.novasys.babel.core.security.BabelCredentialGenerator;
import pt.unl.fct.di.novasys.babel.core.security.BabelIdFromCertExctractor;
import pt.unl.fct.di.novasys.babel.core.security.CredentialGenerator;
import pt.unl.fct.di.novasys.babel.core.security.IdFromCertExtractor;
import pt.unl.fct.di.novasys.babel.core.security.SimpleCredentialGenerator;
import pt.unl.fct.di.novasys.babel.core.security.X509BabelKeyManager;
import pt.unl.fct.di.novasys.babel.core.security.X509BabelTrustManager;
import pt.unl.fct.di.novasys.babel.internal.security.keystore.IdAliasMapper;
import pt.unl.fct.di.novasys.babel.internal.security.keystore.BabelIdAliasMapper;
import pt.unl.fct.di.novasys.network.security.X509IKeyManager;
import pt.unl.fct.di.novasys.network.security.X509ITrustManager;

import java.security.KeyStore.CallbackHandlerProtection;
import java.security.KeyStore.LoadStoreParameter;
import java.security.KeyStore.PasswordProtection;
import java.security.KeyStore.PrivateKeyEntry;

// TODO documentation
public class SecurityConfiguration {

    private static final Logger logger = LogManager.getLogger(SecurityConfiguration.class);

    private static final String DEFAULT_KEY_STORE_TYPE = "PKCS12";

    private Provider provider;

    private boolean initialized = false;

    private String generatedKeyStoreType;

    private String keyStorePath;
    private KeyStore keyStore;
    private LoadStoreParameter keyStoreLoadParameter;
    private ProtectionParameter keyStoreProtection;
    private String writableKeyStorePath;
    private boolean writableKeyStore;

    private String trustStorePath;
    private KeyStore trustStore;
    private LoadStoreParameter trustStoreLoadParameter;
    private ProtectionParameter trustStoreProtection;
    private String writableTrustStorePath;
    private boolean writableTrustStore;

    // TODO KeyStore secretStore for secret keys?

    private X509IKeyManager keyManager;
    private X509ITrustManager trustManager;

    private String defaultAlias;
    private byte[] defaultId;

    private IdAliasMapper idAliasMapper;
    private IdFromCertExtractor idFromCertExtractor;

    private CredentialGenerator credentialGenerator;

    SecurityConfiguration() {
    }

    // Builder methods

    // TODO properties(Properties properties) ?

    private SecurityConfiguration generatedKeyStoreType(String type) {
        generatedKeyStoreType = type;
        return this;
    }

    /**
     * Sets the {@link KeyStore} to be used for self authentication.
     * <p>
     * If the specified file doesn't exist, a new one will be created with an entry
     * generated by the credential generator passed to
     * {@link SecurityConfiguration#credentialGenerator(Supplier)},
     * or the default Babel credential generator if none is given.
     */
    public SecurityConfiguration keyStore(String filePath, String password) {
        return keyStore(filePath).keyStorePassword(password);
    }

    /**
     * Sets the {@link KeyStore} to be used for self authentication.
     * <p>
     * If the specified file doesn't exist, a new one will be created with an entry
     * generated by the credential generator passed to
     * {@link SecurityConfiguration#credentialGenerator(Supplier)},
     * or the default Babel credential generator if none is given.
     */
    public SecurityConfiguration keyStore(String filePath) {
        keyStorePath = filePath;
        return this;
    }

    public SecurityConfiguration keyStore(KeyStore keyStore, String password) {
        return keyStore(keyStore).keyStorePassword(password);
    }

    public SecurityConfiguration keyStore(KeyStore keyStore) {
        this.keyStore = keyStore;
        return this;
    }

    public SecurityConfiguration keyStore(LoadStoreParameter keyStoreLoadParameter) {
        this.keyStoreLoadParameter = keyStoreLoadParameter;
        return this;
    }

    /**
     * Allow Babel to write changes to the key store file given through
     * {@value SecurityConfiguration#keyStore(String)}. <b>This may overwrite any
     * changes that might be made concurrently.</b>
     */
    public SecurityConfiguration writableKeyStore() {
        writableKeyStore = true;
        // Set writableKeyStorePath this to keyStorePath later
        return this;
    }

    /**
     * Allow Babel to write to the given key store file. <b>This will overwrite any
     * content on the given file if it already exists.</b>
     */
    public SecurityConfiguration writableKeyStore(String filePath) {
        writableKeyStore = true;
        writableKeyStorePath = filePath;
        return this;
    }

    public SecurityConfiguration keyStorePassword(String password) {
        return keyStoreProtection(new PasswordProtection(password.toCharArray()));
    }

    /**
     * @see KeyStore.CallbackHandlerProtection
     * @see KeyStore.PasswordProtection
     */
    public SecurityConfiguration keyStoreProtection(ProtectionParameter protection) {
        keyStoreProtection = protection;
        return this;
    }

    public SecurityConfiguration trustStore(String filePath) {
        trustStorePath = filePath;
        return this;
    }

    public SecurityConfiguration trustStore(KeyStore trustStore) {
        this.trustStore = trustStore;
        return this;
    }

    public SecurityConfiguration trustStore(LoadStoreParameter trustStoreLoadParameter) {
        this.trustStoreLoadParameter = trustStoreLoadParameter;
        return this;
    }

    /**
     * Allow Babel to write changes to the key store file given through
     * {@value SecurityConfiguration#trustStore(String)}. <b>This may overwrite any
     * changes that might be made concurrently.</b>
     */
    public SecurityConfiguration writableTrustStore() {
        writableTrustStore = true;
        // Set writableTrustStorePath this to trustStorePath later
        return this;
    }

    /**
     * Allow Babel to write to the given trust store file. <b>This will overwrite
     * any
     * content on the given file if it already exists.</b>
     */
    public SecurityConfiguration writableTrustStore(String filePath) {
        writableTrustStore = true;
        writableTrustStorePath = filePath;
        return this;
    }

    public SecurityConfiguration trustStorePassword(String password) {
        return trustStoreProtection(new PasswordProtection(password.toCharArray()));
    }

    public SecurityConfiguration trustStoreProtection(ProtectionParameter protection) {
        trustStoreProtection = protection;
        return this;
    }

    public SecurityConfiguration keyManager(X509IKeyManager keyManager) {
        this.keyManager = keyManager;
        return this;
    }

    public SecurityConfiguration trustManager(X509ITrustManager trustManager) {
        this.trustManager = trustManager;
        return this;
    }

    // TODO set babel trust manager policy?

    public SecurityConfiguration defaultIdAlias(String alias) {
        defaultAlias = alias;
        return this;
    }

    public SecurityConfiguration defaultId(byte[] id) {
        defaultId = id;
        return this;
    }

    public SecurityConfiguration idAliasMapper(IdAliasMapper idAliasMapper) {
        this.idAliasMapper = idAliasMapper;
        return this;
    }

    public SecurityConfiguration idFromCertExtractor(IdFromCertExtractor idFromCertExtractor) {
        this.idFromCertExtractor = idFromCertExtractor;
        return this;
    }

    public SecurityConfiguration credentialGenerator(CredentialGenerator credentialGenerator) {
        this.credentialGenerator = credentialGenerator;
        return this;
    }

    public SecurityConfiguration credentialGenerator(SimpleCredentialGenerator credentialGenerator) {
        this.credentialGenerator = credentialGenerator;
        return this;
    }

    // Internal methods

    private char[] getPassword(ProtectionParameter protParam, String storeName)
            throws IOException, UnsupportedCallbackException {
        if (protParam instanceof PasswordProtection pwdProt) {
            return pwdProt.getPassword();
        } else if (protParam instanceof CallbackHandlerProtection callbackProt) {
            var callback = new PasswordCallback("Password for " + storeName, false);
            callbackProt.getCallbackHandler().handle(new Callback[] { callback });
            return callback.getPassword();
        } else {
            return null;
        }
    }

    private void throwNull(String variable) throws IllegalStateException {
        throw new IllegalStateException(
                "Tried initializing the security config but required " + variable + " was never set.");
    }

    private KeyStore newKeyStoreWithGeneratedId() throws CertificateException {
        try {
            var store = KeyStore.getInstance(DEFAULT_KEY_STORE_TYPE, provider);
            putGeneratedId(store, new PasswordProtection(null));
        } catch (KeyStoreException e) {
            throw new AssertionError(e); // Won't happen
        }
    }

    private void putGeneratedId(KeyStore store, ProtectionParameter protParam)
            throws CertificateException, KeyStoreException {
        PrivateKeyEntry entry = credentialGenerator.generateRandomCredentials();
        byte[] id = idFromCertExtractor.extractId(entry.getCertificate());
        String alias = idAliasMapper.getAlias(id);

        if (idAliasMapper.getDefaultAlias() == null)
            idAliasMapper.setDefaultAliasAndId(alias, id);

        store.setEntry(alias, entry, protParam);
    }

    private KeyStore keyStoreFromFile(String path, ProtectionParameter protParam, boolean generateFirstId,
            boolean writeIfPresent, LoadStoreParameter loadParam)
            throws IOException, KeyStoreException, NoSuchAlgorithmException,
            CertificateException, UnsupportedCallbackException {
        boolean write = writeIfPresent;
        File file = new File(path);

        KeyStore store;
        if (file.exists()) {
            store = loadParam != null
                    ? KeyStore.getInstance(file, loadParam)
                    : KeyStore.Builder.newInstance(file, protParam).getKeyStore();
        } else {
            file.createNewFile();
            store = KeyStore.getInstance(generatedKeyStoreType, provider);
            write = true;
        }

        if (generateFirstId && store.size() == 0)
            putGeneratedId(store, protParam);

        if (write)
            if (loadParam != null)
                store.store(loadParam);
            else
                store.store(new FileOutputStream(file), getPassword(protParam, path));

        return store;
    }

    void initialize() throws IllegalStateException, IOException, KeyStoreException, NoSuchAlgorithmException,
            CertificateException, UnsupportedCallbackException {
        provider = new BouncyCastleProvider();
        Security.addProvider(provider);

        // Init key store
        if (credentialGenerator == null)
            credentialGenerator = new BabelCredentialGenerator();

        if (keyStoreProtection == null) {
            String password = System.getProperty("javax.net.ssl.keyStorePassword");
            keyStoreProtection = new PasswordProtection(password != null ? password.toCharArray() : null);
        }

        if (generatedKeyStoreType == null)
            generatedKeyStoreType = DEFAULT_KEY_STORE_TYPE;

        if (keyStore == null) {
            if (keyStorePath == null)
                keyStorePath = System.getProperty("javax.net.ssl.keyStore");

            if (keyStorePath != null)
                keyStore = keyStoreFromFile(keyStorePath, keyStoreProtection, true, writableKeyStore,
                        keyStoreLoadParameter);
            else
                keyStore = newKeyStoreWithGeneratedId();
        }
        // TODO something when writableKeyStore

        // Init trust store
        if (trustStoreProtection == null) {
            String password = System.getProperty("javax.net.ssl.trustStorePassword");
            trustStoreProtection = new PasswordProtection(password != null ? password.toCharArray() : null);
        }

        if (trustStore == null) {
            if (trustStorePath == null)
                trustStorePath = System.getProperty("javax.net.ssl.trustStore");

            if (trustStorePath != null)
                trustStore = keyStoreFromFile(trustStorePath, trustStoreProtection, false, writableTrustStore,
                        trustStoreLoadParameter);
            else
                trustStore = null;
        }
        // TODO something when writableKeyStore

        // Init key manager
        if (idAliasMapper == null)
            idAliasMapper = new BabelIdAliasMapper();

        if (defaultAlias != null)
            if (defaultId != null)
                idAliasMapper.setDefaultAliasAndId(defaultAlias, defaultId);
            else
                idAliasMapper.setDefaultAlias(defaultAlias);
        else if (defaultId != null)
            idAliasMapper.setDefaultId(defaultId);

        if (keyManager == null)
            keyManager = new X509BabelKeyManager(keyStore, keyStoreProtection, idAliasMapper);

        // Init trust manager
        if (idFromCertExtractor == null)
            idFromCertExtractor = new BabelIdFromCertExctractor();

        if (trustManager == null)
            trustManager = new X509BabelTrustManager(trustStore, trustStoreProtection, idFromCertExtractor);

        // TODO anything else?

        initialized = true;

        // TODO build the cryptography core
    }

    boolean isInitialized() {
        return initialized;
    }
}
