package pt.unl.fct.di.novasys.babel.core;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.security.KeyStore;
import java.security.Provider;
import java.security.KeyStore.ProtectionParameter;
import java.security.KeyStoreException;
import java.security.NoSuchAlgorithmException;
import java.util.function.Supplier;

import javax.security.auth.callback.Callback;
import javax.security.auth.callback.PasswordCallback;
import javax.security.auth.callback.UnsupportedCallbackException;

import java.security.Security;
import java.security.cert.CertificateException;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.bouncycastle.jce.provider.BouncyCastleProvider;

import pt.unl.fct.di.novasys.babel.internal.security.keystore.IdAliasMapper;
import pt.unl.fct.di.novasys.network.security.X509IKeyManager;
import pt.unl.fct.di.novasys.network.security.X509ITrustManager;

import java.security.KeyStore.CallbackHandlerProtection;
import java.security.KeyStore.LoadStoreParameter;
import java.security.KeyStore.PasswordProtection;
import java.security.KeyStore.PrivateKeyEntry;

// TODO documentation
public class SecurityConfiguration {

    private static final Logger logger = LogManager.getLogger(SecurityConfiguration.class);

    private static final String DEFAULT_KEY_STORE_TYPE = "PKCS12";

    private Provider provider;

    private boolean initialized = false;

    private String keyStorePath;
    private KeyStore keyStore;
    private LoadStoreParameter keyStoreLoadParameter;
    private ProtectionParameter keyStoreProtection;
    private String writableKeyStorePath;
    private boolean writableKeyStore;

    private String trustStorePath;
    private KeyStore trustStore;
    private LoadStoreParameter trustStoreLoadParameter;
    private ProtectionParameter trustStoreProtection;
    private String writableTrustStorePath;
    private boolean writableTrustStore;

    private X509IKeyManager keyManager;
    private X509ITrustManager trustManager;

    private String defaultAlias;
    private byte[] defaultId;

    private IdAliasMapper idAliasMapper;

    private Supplier<PrivateKeyEntry> credentialGenerator;

    SecurityConfiguration() {
    }

    // Builder methods

    // TODO properties(Properties properties) ?

    /**
     * Sets the {@link KeyStore} to be used for self authentication.
     * <p>
     * If the specified file doesn't exist, a new one will be created with an entry
     * generated by the credential generator passed to
     * {@link SecurityConfiguration#credentialGenerator(Supplier)},
     * or the default Babel credential generator if none is given.
     */
    public SecurityConfiguration keyStore(String filePath, String password) {
        return keyStore(filePath).keyStorePassword(password);
    }

    /**
     * Sets the {@link KeyStore} to be used for self authentication.
     * <p>
     * If the specified file doesn't exist, a new one will be created with an entry
     * generated by the credential generator passed to
     * {@link SecurityConfiguration#credentialGenerator(Supplier)},
     * or the default Babel credential generator if none is given.
     */
    public SecurityConfiguration keyStore(String filePath) {
        keyStorePath = filePath;
        return this;
    }

    public SecurityConfiguration keyStore(KeyStore keyStore, String password) {
        return keyStore(keyStore).keyStorePassword(password);
    }

    public SecurityConfiguration keyStore(KeyStore keyStore) {
        this.keyStore = keyStore;
        return this;
    }

    public SecurityConfiguration keyStore(LoadStoreParameter keyStoreLoadParameter) {
        this.keyStoreLoadParameter = keyStoreLoadParameter;
        return this;
    }

    /**
     * Allow Babel to write changes to the key store file given through
     * {@value SecurityConfiguration#keyStore(String)}. <b>This may overwrite any
     * changes that might be made concurrently.</b>
     */
    public SecurityConfiguration writableKeyStore() {
        writableKeyStore = true;
        // Set writableKeyStorePath this to keyStorePath later
        return this;
    }

    /**
     * Allow Babel to write to the given key store file. <b>This will overwrite any
     * content on the given file if it already exists.</b>
     */
    public SecurityConfiguration writableKeyStore(String filePath) {
        writableKeyStore = true;
        writableKeyStorePath = filePath;
        return this;
    }

    public SecurityConfiguration keyStorePassword(String password) {
        return keyStoreProtection(new PasswordProtection(password.toCharArray()));
    }

    /**
     * @see KeyStore.CallbackHandlerProtection
     * @see KeyStore.PasswordProtection
     */
    public SecurityConfiguration keyStoreProtection(ProtectionParameter protection) {
        keyStoreProtection = protection;
        return this;
    }

    public SecurityConfiguration trustStore(String filePath) {
        trustStorePath = filePath;
        return this;
    }

    public SecurityConfiguration trustStore(KeyStore trustStore) {
        this.trustStore = trustStore;
        return this;
    }

    public SecurityConfiguration trustStore(LoadStoreParameter trustStoreLoadParameter) {
        this.trustStoreLoadParameter = trustStoreLoadParameter;
        return this;
    }

    /**
     * Allow Babel to write changes to the key store file given through
     * {@value SecurityConfiguration#trustStore(String)}. <b>This may overwrite any
     * changes that might be made concurrently.</b>
     */
    public SecurityConfiguration writableTrustStore() {
        writableTrustStore = true;
        // Set writableTrustStorePath this to trustStorePath later
        return this;
    }

    /**
     * Allow Babel to write to the given trust store file. <b>This will overwrite
     * any
     * content on the given file if it already exists.</b>
     */
    public SecurityConfiguration writableTrustStore(String filePath) {
        writableTrustStore = true;
        writableTrustStorePath = filePath;
        return this;
    }

    public SecurityConfiguration trustStorePassword(String password) {
        return trustStoreProtection(new PasswordProtection(password.toCharArray()));
    }

    public SecurityConfiguration trustStoreProtection(ProtectionParameter protection) {
        trustStoreProtection = protection;
        return this;
    }

    public SecurityConfiguration keyManager(X509IKeyManager keyManager) {
        this.keyManager = keyManager;
        return this;
    }

    public SecurityConfiguration trustManager(X509ITrustManager trustManager) {
        this.trustManager = trustManager;
        return this;
    }

    // TODO set babel trust manager policy?

    public SecurityConfiguration defaultIdAlias(String alias) {
        defaultAlias = alias;
        return this;
    }

    public SecurityConfiguration defaultId(byte[] id) {
        defaultId = id;
        return this;
    }

    public SecurityConfiguration idAliasMapper(IdAliasMapper idAliasMapper) {
        this.idAliasMapper = idAliasMapper;
        return this;
    }

    public SecurityConfiguration credentialGenerator(Supplier<PrivateKeyEntry> credentialGenerator) {
        this.credentialGenerator = credentialGenerator;
        return this;
    }

    // Internal methods

    private char[] getPassword(ProtectionParameter protParam, String storeName)
            throws IOException, UnsupportedCallbackException {
        if (protParam instanceof PasswordProtection pwdProt) {
            return pwdProt.getPassword();
        } else if (protParam instanceof CallbackHandlerProtection callbackProt) {
            var callback = new PasswordCallback("Password for " + storeName, false);
            callbackProt.getCallbackHandler().handle(new Callback[] { callback });
            return callback.getPassword();
        } else {
            return null;
        }
    }

    private void throwNull(String variable) throws IllegalStateException {
        throw new IllegalStateException(
                "Tried initializing the security config but required " + variable + " was never set.");
    }

    private KeyStore newKeyStore() {
        return null; // TODO
    }

    private KeyStore keyStoreFromFile(String path, ProtectionParameter protParam) throws IOException, KeyStoreException,
            NoSuchAlgorithmException, CertificateException, UnsupportedCallbackException {
        KeyStore store;
        File file = new File(path);
        if (file.exists()) {
            store = KeyStore.Builder.newInstance(file, protParam).getKeyStore();
        } else {
            file.createNewFile();
            store = newKeyStore();
            store.store(new FileOutputStream(file), getPassword(protParam, path));
        }
        return store;
    }

    private KeyStore keyStoreFromFile(String path, LoadStoreParameter loadParam)
            throws KeyStoreException, NoSuchAlgorithmException, CertificateException, IOException {
        KeyStore store;
        File file = new File(path);
        if (file.exists()) {
            store = KeyStore.getInstance(file, loadParam);
        } else {
            file.createNewFile();
            store = newKeyStore();
            store.store(loadParam);
        }
        return store;
    }

    void initialize() throws IllegalStateException, IOException, KeyStoreException, NoSuchAlgorithmException,
            CertificateException, UnsupportedCallbackException {
        provider = new BouncyCastleProvider();
        Security.addProvider(provider);

        // Init key store
        if (keyStoreProtection == null) {
            String password = System.getProperty("javax.net.ssl.keyStorePassword");
            keyStoreProtection = new PasswordProtection(password != null ? password.toCharArray() : null);
        }

        if (keyStore == null) {
            if (keyStorePath == null)
                keyStorePath = System.getProperty("javax.net.ssl.keyStore");

            if (keyStorePath != null)
                if (keyStoreLoadParameter != null)
                    keyStore = keyStoreFromFile(keyStorePath, keyStoreLoadParameter);
                else
                    keyStore = keyStoreFromFile(keyStorePath, keyStoreProtection);
            else
                keyStore = newKeyStore();
        }
        // TODO something when writableKeyStore

        // Init trust store
        if (trustStoreProtection == null) {
            String password = System.getProperty("javax.net.ssl.trustStorePassword");
            trustStoreProtection = new PasswordProtection(password != null ? password.toCharArray() : null);
        }

        if (trustStore == null) {
            if (trustStorePath == null)
                trustStorePath = System.getProperty("javax.net.ssl.trustStore");
            // ...
        }

        // TODO

        initialized = true;
    }

    boolean isInitialized() {
        return initialized;
    }
}
