package pt.unl.fct.di.novasys.babel.internal.security;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.security.KeyStore;
import java.security.KeyStore.CallbackHandlerProtection;
import java.security.KeyStore.LoadStoreParameter;
import java.security.KeyStore.PasswordProtection;
import java.security.KeyStore.PrivateKeyEntry;
import java.security.KeyStore.ProtectionParameter;
import java.security.KeyStoreException;
import java.security.NoSuchAlgorithmException;
import java.security.Provider;
import java.security.Security;
import java.security.cert.CertificateException;

import javax.security.auth.callback.Callback;
import javax.security.auth.callback.PasswordCallback;
import javax.security.auth.callback.UnsupportedCallbackException;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.bouncycastle.jce.provider.BouncyCastleProvider;

import pt.unl.fct.di.novasys.babel.core.security.IdentityGenerator;
import pt.unl.fct.di.novasys.babel.core.security.IdFromCertExtractor;
import pt.unl.fct.di.novasys.babel.core.security.SimpleIdentityGenerator;
import pt.unl.fct.di.novasys.network.security.X509IKeyManager;
import pt.unl.fct.di.novasys.network.security.X509ITrustManager;

// TODO documentation
// TODO MAKE THIS BE BASED ON PROPS, AND NOT AS A BUILDER FOR THE USER. ALL CONFIGURATION MUST BE KNOWN AT THE FIRST BABEL.GETINSTANCE
public class SecurityConfiguration {

    private static final Logger logger = LogManager.getLogger(SecurityConfiguration.class);

    private static final String DEFAULT_KEY_STORE_TYPE = "PKCS12";

    private boolean initialized = false;

    private String generatedKeyStoreType;

    private String keyStorePath;
    private KeyStore keyStore;
    private LoadStoreParameter keyStoreLoadParameter;
    private ProtectionParameter keyStoreProtection;
    private String writableKeyStorePath;
    private boolean writableKeyStore;

    private String trustStorePath;
    private KeyStore trustStore;
    private LoadStoreParameter trustStoreLoadParameter;
    private ProtectionParameter trustStoreProtection;
    private String writableTrustStorePath;
    private boolean writableTrustStore;

    private String secretStorePath;
    private KeyStore secretStore;
    private LoadStoreParameter secretStoreLoadParameter;
    private ProtectionParameter secretStoreProtection;
    private String writableSecretStorePath;
    private boolean writableSecretStore;

    private X509IKeyManager keyManager;
    private X509ITrustManager trustManager;

    private String defaultAlias;
    private byte[] defaultId;

    private IdFromCertExtractor idFromCertExtractor;
    private IdentityGenerator identityGenerator;

    private IdAliasMapper _idAliasMapper;
    private Provider _provider;

    public SecurityConfiguration() {
    }

    // Builder methods

    // TODO make read and interpret babel config file

    public SecurityConfiguration generatedKeyStoreType(String type) {
        generatedKeyStoreType = type;
        return this;
    }

    /**
     * Sets the {@link KeyStore} to be used for self authentication.
     * <p>
     * If the specified file doesn't exist, a new one will be created with an entry
     * generated by the credential generator passed to
     * {@link SecurityConfiguration#credentialGenerator(IdentityGenerator)},
     * or the default Babel credential generator if none is given.
     */
    public SecurityConfiguration keyStore(String filePath, String password) {
        return keyStore(filePath).keyStorePassword(password);
    }

    /**
     * Sets the {@link KeyStore} to be used for self authentication.
     * <p>
     * If the specified file doesn't exist, a new one will be created with an entry
     * generated by the credential generator passed to
     * {@link SecurityConfiguration#credentialGenerator(IdentityGenerator)},
     * or the default Babel credential generator if none is given.
     */
    public SecurityConfiguration keyStore(String filePath) {
        keyStorePath = filePath;
        return this;
    }

    public SecurityConfiguration keyStore(KeyStore keyStore, String password) {
        return keyStore(keyStore).keyStorePassword(password);
    }

    public SecurityConfiguration keyStore(KeyStore keyStore) {
        this.keyStore = keyStore;
        return this;
    }

    public SecurityConfiguration keyStore(LoadStoreParameter keyStoreLoadParameter) {
        this.keyStoreLoadParameter = keyStoreLoadParameter;
        return this;
    }

    /**
     * Allow Babel to write changes to the key store file given through
     * {@link SecurityConfiguration#keyStore(String)}. <b>This may overwrite any
     * changes that might be made concurrently.</b>
     */
    public SecurityConfiguration writableKeyStore() {
        writableKeyStore = true;
        // Set writableKeyStorePath to keyStorePath during init()
        return this;
    }

    /**
     * Allow Babel to write to the given key store file. <b>This will overwrite any
     * content on the given file if it already exists.</b>
     */
    public SecurityConfiguration writableKeyStore(String filePath) {
        writableKeyStore = true;
        writableKeyStorePath = filePath;
        return this;
    }

    public SecurityConfiguration keyStorePassword(String password) {
        return keyStoreProtection(new PasswordProtection(password.toCharArray()));
    }

    /**
     * @see KeyStore.CallbackHandlerProtection
     * @see KeyStore.PasswordProtection
     */
    public SecurityConfiguration keyStoreProtection(ProtectionParameter protection) {
        keyStoreProtection = protection;
        return this;
    }

    public SecurityConfiguration trustStore(String filePath) {
        trustStorePath = filePath;
        return this;
    }

    public SecurityConfiguration trustStore(KeyStore trustStore) {
        this.trustStore = trustStore;
        return this;
    }

    public SecurityConfiguration trustStore(LoadStoreParameter trustStoreLoadParameter) {
        this.trustStoreLoadParameter = trustStoreLoadParameter;
        return this;
    }

    /**
     * Allow Babel to write changes to the key store file given through
     * {@link SecurityConfiguration#trustStore(String)}. <b>This may overwrite any
     * changes that might be made concurrently.</b>
     */
    public SecurityConfiguration writableTrustStore() {
        writableTrustStore = true;
        // Set writableTrustStorePath to trustStorePath during init()
        return this;
    }

    /**
     * Allow Babel to write to the given trust store file. <b>This will overwrite
     * any
     * content on the given file if it already exists.</b>
     */
    public SecurityConfiguration writableTrustStore(String filePath) {
        writableTrustStore = true;
        writableTrustStorePath = filePath;
        return this;
    }

    public SecurityConfiguration trustStorePassword(String password) {
        return trustStoreProtection(new PasswordProtection(password.toCharArray()));
    }

    public SecurityConfiguration trustStoreProtection(ProtectionParameter protection) {
        trustStoreProtection = protection;
        return this;
    }

    public SecurityConfiguration secretStore(String filePath) {
        secretStorePath = filePath;
        return this;
    }

    public SecurityConfiguration secretStore(KeyStore secretStore) {
        this.secretStore = secretStore;
        return this;
    }

    public SecurityConfiguration secretStore(LoadStoreParameter secretStoreLoadParameter) {
        this.secretStoreLoadParameter = secretStoreLoadParameter;
        return this;
    }

    /**
     * Allow Babel to write changes to the key store file given through
     * {@link SecurityConfiguration#secretStore(String)}. <b>This may overwrite any
     * changes that might be made concurrently.</b>
     */
    public SecurityConfiguration writablesecretStore() {
        writableSecretStore = true;
        // Set writableSecretStorePath to secretStorePath during init()
        return this;
    }

    /**
     * Allow Babel to write to the given secret store file. <b>This will overwrite
     * any
     * content on the given file if it already exists.</b>
     */
    public SecurityConfiguration writableSecretStore(String filePath) {
        writableSecretStore = true;
        writableSecretStorePath = filePath;
        return this;
    }

    public SecurityConfiguration secretStorePassword(String password) {
        return secretStoreProtection(new PasswordProtection(password.toCharArray()));
    }

    public SecurityConfiguration secretStoreProtection(ProtectionParameter protection) {
        secretStoreProtection = protection;
        return this;
    }

    public SecurityConfiguration keyManager(X509IKeyManager keyManager) {
        this.keyManager = keyManager;
        return this;
    }

    public SecurityConfiguration trustManager(X509ITrustManager trustManager) {
        this.trustManager = trustManager;
        return this;
    }

    // TODO set babel trust manager policy?

    public SecurityConfiguration defaultIdAlias(String alias) {
        defaultAlias = alias;
        return this;
    }

    public SecurityConfiguration defaultId(byte[] id) {
        defaultId = id;
        return this;
    }

    public SecurityConfiguration idFromCertExtractor(IdFromCertExtractor idFromCertExtractor) {
        this.idFromCertExtractor = idFromCertExtractor;
        return this;
    }

    public SecurityConfiguration credentialGenerator(IdentityGenerator credentialGenerator) {
        this.identityGenerator = credentialGenerator;
        return this;
    }

    public SecurityConfiguration credentialGenerator(SimpleIdentityGenerator credentialGenerator) {
        this.identityGenerator = credentialGenerator;
        return this;
    }

    // Internal methods

    private char[] getPassword(ProtectionParameter protParam, String storeName)
            throws IOException, UnsupportedCallbackException {
        if (protParam instanceof PasswordProtection pwdProt) {
            return pwdProt.getPassword();
        } else if (protParam instanceof CallbackHandlerProtection callbackProt) {
            var callback = new PasswordCallback("Password for " + storeName, false);
            callbackProt.getCallbackHandler().handle(new Callback[] { callback });
            return callback.getPassword();
        } else {
            return null;
        }
    }

    private KeyStore newKeyStoreWithGeneratedId() throws CertificateException, KeyStoreException {
        var store = KeyStore.getInstance(DEFAULT_KEY_STORE_TYPE, _provider);
        try {
            store.load(null, null);
        } catch (NoSuchAlgorithmException | CertificateException | IOException never) {
            throw new AssertionError(never);
        }
        putGeneratedId(store, new PasswordProtection("".toCharArray()));
        return store;
    }

    private void putGeneratedId(KeyStore store, ProtectionParameter protParam)
            throws CertificateException, KeyStoreException {
        PrivateKeyEntry entry = identityGenerator.generateRandomCredentials();
        byte[] id = idFromCertExtractor.extractIdentity(entry.getCertificate());
        String alias = PeerIdEncoder.encodeToString(id);

        logger.debug("Generated id " + alias);

        store.setEntry(alias, entry, protParam);
    }

    private KeyStore keyStoreFromFile(String path, ProtectionParameter protParam, boolean generateFirstId,
            String writePath, LoadStoreParameter loadParam)
            throws IOException, KeyStoreException, NoSuchAlgorithmException,
            CertificateException, UnsupportedCallbackException {
        File file = new File(path);
        char[] password = getPassword(protParam, path);

        KeyStore store;
        if (file.exists()) {
            store = loadParam != null
                    ? KeyStore.getInstance(file, loadParam)
                    : KeyStore.Builder.newInstance(file, protParam).getKeyStore();
        } else {
            logger.debug("No KeyStore {} found. Creating a new one...", path);
            file.createNewFile();
            store = KeyStore.getInstance(generatedKeyStoreType, _provider);

            if (loadParam != null)
                store.load(loadParam);
            else
                store.load(null, password);

            if (writePath == null)
                writePath = path;
        }

        if (generateFirstId && store.size() == 0) {
            logger.debug("KeyStore empty. Generating an id...");
            putGeneratedId(store, protParam);
        }

        if (writePath != null)
            if (loadParam != null)
                store.store(loadParam);
            else
                store.store(new FileOutputStream(writePath), getPassword(protParam, path));

        return store;
    }

    void initialize() throws IllegalStateException, IOException, KeyStoreException, NoSuchAlgorithmException,
            CertificateException, UnsupportedCallbackException {
        if (initialized) {
            throw new IllegalStateException("Tried initializing security core twice.");
        }

        _provider = new BouncyCastleProvider();
        Security.addProvider(_provider);

        // Init key store
        if (idFromCertExtractor == null) {
            var handler = new BabelCredentialHandler();
            idFromCertExtractor = handler;
            if (identityGenerator == null)
                identityGenerator = handler;
        }

        if (identityGenerator == null)
            identityGenerator = new BabelCredentialHandler();

        if (keyStoreProtection == null) {
            String password = System.getProperty("javax.net.ssl.keyStorePassword");
            keyStoreProtection = new PasswordProtection(password != null ? password.toCharArray() : "".toCharArray());
        }

        if (generatedKeyStoreType == null)
            generatedKeyStoreType = DEFAULT_KEY_STORE_TYPE;

        if (keyStorePath == null)
            keyStorePath = System.getProperty("javax.net.ssl.keyStore");

        if (writableKeyStore && writableKeyStorePath == null)
            writableKeyStorePath = keyStorePath;

        if (keyStore == null) {
            if (keyStorePath != null) {
                keyStore = keyStoreFromFile(keyStorePath, keyStoreProtection,
                        true, writableKeyStorePath, keyStoreLoadParameter);
            } else {
                logger.debug("Generating ephemeral keystore with single identity...");
                keyStore = newKeyStoreWithGeneratedId();
            }
        }

        // Init trust store
        if (trustStoreProtection == null) {
            String password = System.getProperty("javax.net.ssl.trustStorePassword");
            trustStoreProtection = new PasswordProtection(password != null ? password.toCharArray() : null);
        }

        if (trustStorePath == null)
            trustStorePath = System.getProperty("javax.net.ssl.trustStore");

        if (writableTrustStore && writableTrustStorePath == null)
            writableTrustStorePath = trustStorePath;

        if (trustStore == null && trustStorePath != null) {
            trustStore = keyStoreFromFile(trustStorePath, trustStoreProtection,
                    false, writableTrustStorePath, trustStoreLoadParameter);
        }

        // Init secret store
        if (secretStoreProtection == null)
            secretStoreProtection = new PasswordProtection(null);

        if (writableSecretStore && writableSecretStorePath == null)
            writableSecretStorePath = secretStorePath;

        if (secretStore == null && secretStorePath != null) {
            secretStore = keyStoreFromFile(secretStorePath, secretStoreProtection,
                    false, writableSecretStorePath, secretStoreLoadParameter);
        }

        // Init key manager
        _idAliasMapper = new IdAliasMapper().populateFromPrivateKeyStore(keyStore, keyStoreProtection,
                idFromCertExtractor);
        if (defaultAlias != null)
            _idAliasMapper.setDefaultAlias(defaultAlias);
        else if (defaultId != null)
            _idAliasMapper.setDefaultId(defaultId);

        if (keyManager == null)
            keyManager = new X509BabelKeyManager(keyStore, keyStoreProtection, _idAliasMapper);

        // Init trust manager
        if (trustManager == null)
            trustManager = new X509BabelTrustManager(trustStore, trustStoreProtection, idFromCertExtractor);

        // TODO anything else?

        initialized = true;

        //securityCore = new SecurityCore(keyStore, keyStoreProtection, writableKeyStorePath, secretStore,
                //secretStoreProtection, writableSecretStorePath, trustStore, trustStoreProtection,
                //writableTrustStorePath, keyManager, trustManager, _idAliasMapper, credentialGenerator,
                //idFromCertExtractor);
    }

    boolean isInitialized() {
        return initialized;
    }

    /*
    SecurityCore core() {
        if (initialized) {
            return securityCore;
        } else {
            logger.error(
                    "Tried accessing SecurityCore before it was initialized. Have you marked your protocols with @SecureProtocol?");
            throw new IllegalStateException("Tried accessing SecurityCore before it was initialized.");
        }
    }
    */

    public IdentityGenerator getIdentityGenerator() {
        return identityGenerator;
    }

    public IdFromCertExtractor getIdFromCertExtractor() {
        return idFromCertExtractor;
    }

    public KeyStore getKeyStore() {
        return keyStore;
    }

}
